// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI PARTICLE SWARM OPTIMISATION FOR GENETIC PROGRAMMING

// THIS FILE PERTAINS TOWARDS THE PSO ALGORITHM FOR OPTIMISING
// GENETIC PROGRAMMING PARAMETERS AND FITNESS EVALUATION

// SPECIFICALLY, THIS VERSION OF THE PSO IMPLEMENTATION
// AIMS TO PROVIDE AN UNDERSTANDING FOR HOW TO MITIGATE AN ISSUE
// RELATED TO THE DAILY DEMAND OF A LOGISTICS COMPANY

// THIS VERSION FOCUSSES ON THE SIMPLIFICATION OF THE CURRENT
// PSO IMPLEMENTATION - TO PROVIDE A POINT OF COMPARISON TO PROPERLY
// DISCERN THE BENEFITS OF EITHER OR

// NESTED INCLUDES

#include "pso_simple.h"

int main(void)
{
    printf("HARRY CLARK - CS3_CI EXPERIMENTAL STUDY\n");

    PSO_SIMPLE PS;
    PSO_SIMPLE_INIT(&PS, PSO_MAX_DEM);

    return 0;
}