// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI PARTICLE SWARM OPTIMISATION FOR GENETIC PROGRAMMING

// THIS FILE PERTAINS TOWARDS THE PSO ALGORITHM FOR OPTIMISING
// GENETIC PROGRAMMING PARAMETERS AND FITNESS EVALUATION

// SPECIFICALLY, THIS VERSION OF THE PSO IMPLEMENTATION
// AIMS TO PROVIDE AN UNDERSTANDING FOR HOW TO MITIGATE AN ISSUE
// RELATED TO THE DAILY DEMAND OF A LOGISTICS COMPANY

// THIS VERSION FOCUSSES ON THE SIMPLIFICATION OF THE CURRENT
// PSO IMPLEMENTATION - TO PROVIDE A POINT OF COMPARISON TO PROPERLY
// DISCERN THE BENEFITS OF EITHER OR

#ifndef PSO_SIMPLE_H
#define PSO_SIMPLE_H

// NESTED INCLUDES

#include "../pso.h"

#if defined(USE_SIMPLE)
    #define USE_SIMPLE
#else
    #define USE_SIMPLE

    #define         PSO_SIMPLE_INERTIA         0.729
    #define         PSO_SIMPLE_COG             1.49
    #define         PSO_SIMPLE_SOC             1.49

    // SIMPLE STATE MACHINE FOR ALL OF THE CORRESPONDENCE
    // WITHIN THE PSO - WE WILL ONLY USE THE MOST BASIC OF FEATURES
    typedef struct
    {
        int DIMENSIONS;
        PSO_BOUND BOUNDS[PSO_MAX_DEM];
        PSO_DATASET DATASET;
        PSO_SWARM SWARM;
        PSO_STATS STATS;

    } PSO_SIMPLE;

    typedef PSO_SIMPLE* PS;
    typedef PSO_PARTICLE* PARTICLE;
    typedef PSO_BOUND* BOUNDS;

    int PSO_SIMPLE_INIT(PS, int);
    void PSO_SIMPLE_BOUNDS(PS, int, double, double);
    void PSO_SIMPLE_OPTIMSISE(PS);

#endif
#endif
