// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI PARTICLE SWARM OPTIMISATION FOR ANTENNA ARRAY DESIGN

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF THE PROGRAM

// NESTED INCLUDES

#include "pso.h"

#define         PSO_NUM_ATTENNAE            8
#define         PSO_TARGET_ANGLE            M_PI / 4.0 

int main(void)
{    
    printf("========================================\n");
    printf("HARRY CLARK - CS3_CI PSO IMPLEMENTATION\n");
    printf("========================================\n");

    PSO STATE;
    time_t START_TIME = time(NULL);
    double TOTAL_TIME = difftime(time(NULL), START_TIME);    
    
    if(PSO_INIT(&STATE, PSO_NUM_ATTENNAE, PSO_SIMPLE) != 0)
    {
        PSO_ERROR_HANDLE(NONE, PSO_ERROR_PARTICLE, "FAILED TO INITIALISE PSO%s", "");
        return 1;
    }
    
    // SET BOUNDS FOR ANTENNA PHASE WEIGHTS
    for(int DIM = 0; DIM < PSO_NUM_ATTENNAE; DIM++)
    {
        PSO_SET_BOUNDS(&STATE, DIM, 0.0, 2.0 * M_PI);
    }
    
    if(PSO_OPTIMIZE_ANTENNA(&STATE, PSO_NUM_ATTENNAE, PSO_TARGET_ANGLE) != 0)
    {
        PSO_ERROR_HANDLE(NONE, PSO_ERROR_PARTICLE, "PSO OPTIMIZATION FAILED%s", " ");
        return 1;
    }

    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  NUMBER OF ANTENNAE: %d", PSO_NUM_ATTENNAE);
    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  TARGET ANGLE: %.4f RADIANS (%.2f DEGREES)", 
        PSO_TARGET_ANGLE, PSO_TARGET_ANGLE * 180.0 / M_PI);

    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  PARTICLES: %d", PSO_MAX_PARTICLES);
    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  MAX ITERATIONS: %d", PSO_MAX_ITERATIONS);
    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  TIME LIMIT: %.1f SECONDS", PSO_LIMIT);

    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  FINAL FITNESS: %.6f", STATE.SWARM.GLOBAL_FITNESS);
    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  ITERATIONS COMPLETED: %d", STATE.SWARM.PARTICLE_PARAMS.ITERATION + 1);
    PSO_HANDLE(NONE, PSO_ERROR_NONE, "  TIME ELAPSED: %.2f SECONDS", TOTAL_TIME);

    // DETERMINES HOW MANY CONCURRENT ANTENNAE ARE IN THE SWARM
    for(int DIM = 0; DIM < PSO_NUM_ATTENNAE; DIM++)
    {
        PSO_HANDLE(NONE, PSO_ERROR_NONE, "  ANTENNA %2d: %6.4f RAD (%7.2f DEG)", 
            DIM, 
            STATE.SWARM.GLOBAL_POS[DIM],
            STATE.SWARM.GLOBAL_POS[DIM] * 180.0 / M_PI);
    }

    return 0;
}
