// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND COURSEWORK CONTENTS OF CS3_CI

// NESTED INCLUDES

#include "tsp.h"

int main(int argc, char* argv[])
{
    printf("HARRY CLARK - CS3_CI TSP SOLUTION\n");

    if(argc != 2)
    {
        printf("USAGE: %s --ALGORITHM\n", argv[0]);
        return 1;
    }

    // DISCERN THE ALGO TYPE BASED ON PROVIDED ARG
    TSP_ALGO ALGO = TSP_ALGO_ARG(argv[1]);

    TSP_STATE STATE;    
    TSP_INIT(&STATE, ALGO);

    // 20/10/25
    // COORDS TO DELIBERATELY FORCE THE LOCAL SEARCH TO WORK
    TSP_ADD_CITY(&STATE, "LONDON", 1000, 20);
    TSP_ADD_CITY(&STATE, "PARIS", 344, 500);
    TSP_ADD_CITY(&STATE, "MADRID", 1495, 173);
    TSP_ADD_CITY(&STATE, "SHANGHAI", 5000, 2812);
    TSP_ADD_CITY(&STATE, "TOKYO", 5500, 1500);
    TSP_ADD_CITY(&STATE, "NEW YORK", -3500, 700);
    TSP_ADD_CITY(&STATE, "MANCHESTER", 10000, 8937);

    // ALGO CHOICE WILL NOW DYNAMICALLY EXECUTE
    // PROVIDED ALGO TYPE AS PER THE SWITCH
    TSP_ALGO_CHOICE(&STATE, ALGO);

    return 0;
}
