// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND COURSEWORK CONTENTS OF CS3_CI

// NESTED INCLUDES

#include "tsp.h"

int main(int argc, char* argv[])
{
    printf("HARRY CLARK - CS3_CI TSP SOLUTION\n");

    if(argc != 3)
    {
        printf("USAGE: %s --ALGORITHM\n", argv[0]);
        return 1;
    }

    // DISCERN THE ALGO TYPE BASED ON PROVIDED ARG
    TSP_ALGO ALGO = TSP_ALGO_ARG(argv[1]);
    const char* CSV = argv[2];

    // LOAD THE CORRESPONDENCE OF THE TSP ALGORITHM
    TSP_STATE STATE;   
    TSP_INIT(&STATE, ALGO);

    // LOAD THE COORDS WHICH REPRESENT THE CITIES
    // WITHIN THE TOUR

    if(TSP_LOAD_CSV(&STATE, CSV) != 0)
    {
        TSP_ERROR_HANDLE(NONE, TSP_ERROR_NONE, "FAILED TO LOAD CSV FILE: %s\n", CSV);
        return 1;
    }

    // ALGO CHOICE WILL NOW DYNAMICALLY EXECUTE
    // PROVIDED ALGO TYPE AS PER THE SWITCH
    TSP_ALGO_CHOICE(&STATE, ALGO);

    return 0;
}
