// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND LAB CONTENTS OF CS3_CI

// SPECIFICALLY, THIS VERSION FOCUSSES MORE SO ON THE CONTENTS PERTAINING
// TOWARDS THE COURSEWORK - KEEPING MY ORIGINAL IMPLEMENTATION ADJACENT

// NESTED INCLUDES 

#include "coursework/tsp.h"

int TSP_BEST_DIST;
int TSP_BEST_PATH[TSP_MAX_CITIES + 1];

const char* TSP_ERR_MSG[] =
{
    "OK",
    "INDEX OUT OF BOUNDS",
    "MAX CITIES EXCEEDED",
    "MAX DISTANCE EXCEEDED",
    "MAX VALUE FOR PATHING"
};

// INITIALISE THE ENCOMPASSING BASE FOR THE CURRENT TSP PROBLEM
// THE FOLLIWING WILL LOOK TO DETERMINE THE CITY COUNT, DISTANCES BETWEEN
// CITIES, ETC
//
// ENCORPERATES MATRIX ADDITION TO BE ABLE TO DETERMINE THE BASE
// DISTANCE BETWEEN CITIES
//
// BETWEEN THIS AND MY ORIGINAL TSP IMPLEMENTATION
// IT REMAINS MOSTLY THE SAME BARRING THE FACT THAT 
// THIS INCLUDES LOCAL SEARCH
int TSP_INIT(TSP_STATE* STATE)
{
    if(STATE == NULL) { TSP_MEM_ERROR(STATE); }

    STATE->CITY_COUNT = 0;
    STATE->DIST.SIZE = 0;
    STATE->TOUR.TSP_TOTAL_DIST = 0;
    STATE->TOUR.TSP_CITY_COUNT = 0;
    STATE->ALGO = TSP_TWO_OPT;

    // INITIALISE THE BASIS FOR THE ALGORITHMS BEING USED
    // THIS WILL BE UPDATED TO COMPARE AGAINST OTHER ALGORITHMS WHEN APPROPRIATE
    strcpy(STATE->STAT_DATA.ALGORITHM_A.NAME, TSP_ALGO_TYPE(STATE->ALGO));

    TSP_HANDLE(NONE, TSP_ERROR_NONE, "\nTSP PARAMS:\n ALGORITHM: %s\n", TSP_ALGO_TYPE(STATE->ALGO));
    return 0;
}