// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND LAB CONTENTS OF CS3_CI

// SPECIFICALLY, THIS VERSION FOCUSSES MORE SO ON THE CONTENTS PERTAINING
// TOWARDS THE COURSEWORK - KEEPING MY ORIGINAL IMPLEMENTATION ADJACENT

// NESTED INCLUDES

#include "tsp.h"

// INITIALISE THE BASIS FOR THE ACO PHEROMONE MATRIX
// THE FOLLOWING PRESUPPOSES AN ELITIST STRATEGY WHEREBY THE BEST 
// ANT DEPOSITS EXTRA PHEROMONE 
//
// DEPOSITION IS THE PENULTIMATE RESULT OF THE INCREASE IN PHEROMONE
void TSP_ACO_INIT(TSP_ACO_STATE* ACO, int CITY_COUNT)
{
    // CREATE THE INITIAL PHERMONE UPDATE HEURISTIC
    // THIS IS DONE BY DETERMINING THE CONTRIBUTIONS OF
    // THE ANTS WITHIN THE CYCLE
    
    for(int INDEX = 0; INDEX < CITY_COUNT; INDEX++)
    {
        for(int ITERATOR = 0; ITERATOR < CITY_COUNT; ITERATOR++)
        {
            ACO->PHEROMONE[INDEX][ITERATOR] = TSP_ACO_PHER_RATE;
        }
    }

    ACO->BEST_DIST = INT_MAX;
    TSP_HANDLE(NONE, TSP_ERROR_NONE, 
        "ANT COLONY INITIALISED WITH CURRENT PHERMONE: %d WITH CURRENT BEST DIST %d\n", 
        ACO->PHEROMONE, ACO->BEST_DIST);
}

// CREATE THE BASIS FOR ALL OF THE ENCOMPASSING ACO FUNCTIONALITY
// WHAT MAKES THIS DIFFERENT TO THE ABOVE IS THAT THIS ACTUALLY
// GOES OVER THE ITERATIONS - RATHER THAN JUST INITIALISING THE 
// INDEXXING FOR THE MATRIX

int TSP_ACO_BASE(TSP_STATE* STATE, int MAX_ITER)
{
    TSP_ACO_STATE* ACO_STATE;
    TSP_ACO_INIT(&ACO_STATE, STATE->CITY_COUNT);

    if(ACO_STATE == NULL) goto ACO_NULL;

    ACO_NULL:
        TSP_MEM_ERROR(ACO_STATE);
        TSP_ERROR_HANDLE(ACO, TSP_ERROR_ACO, "WITH CITY COUNT %d\n", STATE->CITY_COUNT);
}
