// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND LAB CONTENTS OF CS3_CI

// NESTED INCLUDES 

#include "tsp.h"

int main(int argc, char* argv[])
{
    printf("HARRY CLARK - CS3_CI TSP SOLUTION\n");

    if(argc != 2)
    {
        printf("USAGE: %s, --ALGORITHM\n", argv[0]);
        return 1;
    }

    // DISCERN THE ALGO TYPE BASED ON PROVIDED ARG
    TSP_ALGO ALGO = TSP_ALGO_ARG(argv[1]);

    TSP_STATE STATE;    
    TSP_INIT(&STATE, ALGO);

    TSP_ADD_CITY(&STATE, "LONDON", 0, 0);
    TSP_ADD_CITY(&STATE, "PARIS", 344, 0);
    TSP_ADD_CITY(&STATE, "MADRID", 1495, 173);
    TSP_ADD_CITY(&STATE, "SHANGHAI", 5000, 2812);

    // ALGO CHOICE WILL NOW DYNAMICALLY EXECUTE
    // PROVIDED ALGO TYPE AS PER THE SWITCH
    TSP_ALGO_CHOICE(&STATE, ALGO);

    return 0;
}
